### ISSUE TITLE
侧边栏消失

### ISSUE THREAD

**Issue by wuxinkuliu** [bakyrd/QQScreenshotSwitch#1]
改成新版截图工具侧边栏消失，改回去就没事了。

**Comment by ilharp** [comment]
我理解了一下，你的意思是 QQScreenshotSwitch 启用 `new` 模式以后，QQ 的主窗口左侧栏会消失？

我能理解你的问题，但这个问题应该和 QQScreenshotSwitch 没有关系。先看下你用的是否是最新的 [v1.0.1](https://github.com/bakyrd/QQScreenshotSwitch/releases/tag/v1.0.1) 版本？如果你使用 LiteLoaderQQNT 的话，LiteLoaderQQNT 使用的哪个版本，有没有安装其他的插件？

另外现在 QQ 应该已经大面积灰度新版截图工具了，理论上不装本软件或者开启 `noop` 模式的话默认就可以用上新版的截图工具了。

**Comment by wuxinkuliu** [comment]
插件是最新版，LiteLoaderQQNT是1.1.2，QQ版本是9.9.11-24815，其他插件已关闭情况下。
原来这样：
![QQ截图20240720152621](https://github.com/user-attachments/assets/db2c3035-b0e4-4ea4-906a-7f59a2608052)
现在这样：
![QQ20240720-152516](https://github.com/user-attachments/assets/0c09181b-0b25-4b3e-ae7a-720de8fc6f93)

**Comment by ilharp** [comment]
因为 QQScreenshotSwitch 本身完全没有与修改界面相关的功能，只有切换新旧版截图的功能，所以我想再确认下：

1. 你的 QQScreenshotSwitch 是最新的 v1.0.1 吗？
1. 出现这样的问题，是只有 QQScreenshotSwitch 模式开到 `new` 模式才会出现的吗？ `noop` 模式下是否还会出现此问题？

**Comment by wuxinkuliu** [comment]
插件是最新的1.0.1，当配置文件改为noop问题消失

**Comment by ilharp** [comment]
感谢帮忙定位问题，这么看确实是 QQScreenshotSwitch 导致了侧边栏的这个问题。我回去后会看下。

**Comment by ilharp** [comment]
确实存在此问题，已在 [v1.0.2](https://github.com/bakyrd/QQScreenshotSwitch/releases/tag/v1.0.2) 中修复，非常感谢发现问题！

**Comment by wuxinkuliu** [comment]
感谢
