### ISSUE TITLE
新版工具调用

### ISSUE THREAD

**Issue by fh1999** [bakyrd/QQScreenshotSwitch#2]
大佬，我想调用新版qq截图上的工具，能提供一个思路吗~

**Comment by ilharp** [comment]
52 上也有人问了这个问题，我做了 [回复](https://www.52pojie.cn/forum.php?mod=redirect&goto=findpost&ptid=1941589&pid=50777109)，我抄在这里：

---

旧版截图工具可以，百度直接搜《逆向调用QQ截图NT》即可

新版截图工具也可以但很麻烦，而且没必要，因为新版截图工具同时需要一个完整的 QQ + 完整的旧版截图工具才能运行，并且占用内存跟 QQ 登录后差不多，独立出来没有什么好处

**Comment by fh1999** [comment]
我主要想调用最新版截图工具的新能力～旧版的没上这个东西

**Comment by ilharp** [comment]
单纯调用的话挺简单的，但需要 QQ 运行 + 登录；想脱离 QQ 登录情况独立出截图工具的部分的话就比较麻烦了。

**Comment by ilharp** [comment]
单纯调用的话挺简单的，但需要 QQ 运行 + 登录；想脱离 QQ 登录情况独立出截图工具的部分的话就比较麻烦了。
