### ISSUE TITLE
命令行开关修改单个 QQ 进程模式异常

### ISSUE THREAD

**Issue by devil233-ui** [bakyrd/QQScreenshotSwitch#3]
>  9.9.12-26466
LiteLoaderQQNT1.2.0
QQScreenshotSwitch-1.0.2

为什么是新打开了一个进程
![image](https://github.com/user-attachments/assets/6a67d580-4b5f-47cf-9c47-c113918f06e4)
![image](https://github.com/user-attachments/assets/71ecd2e7-2761-4131-8fdb-56eedba11c43)
![image](https://github.com/user-attachments/assets/bf68d965-5f9e-4044-b03f-96eb2efac16c)

**Comment by ilharp** [comment]
命令行开关是用于临时以某种模式启动 QQ 的，不是用来修改配置的，修改配置请在 `.qqsss/config.txt` 里修改
