### ISSUE TITLE
配置文件只要不是noop 就会导致QQ无法启动

### ISSUE THREAD

**Issue by singularity2000** [bakyrd/QQScreenshotSwitch#4]
写于2024年9月6日，使用的是当前的最新版QQ NT 9.9.15.27597，此插件安装的是源代码包
new、old、default都试过了 启动QQ时如图所示
![image](https://github.com/user-attachments/assets/c1e769bb-bdec-4396-95a5-20c640b5b41a)
请大佬更新插件，并在QQ内菜单中 提供更方便进行模式切换的按钮

**Comment by singularity2000** [comment]
我使用此插件的原因：
QQ NT 新版截图工具，游戏等场景下，使用Ctrl+shift+A截图 点击右下角“√”后，有50%的概率出现并没有完成截图的情况，剪贴板是空的。
现在 QQNT 已经默认使用新版截图工具了，使用此插件尝试换回旧版截图。如果有大佬懂这个问题的解决方法，不胜感激。

**Comment by forgetmelodyXL** [comment]
我跟你的问题一模一样

**Comment by ilharp** [comment]
新版修了还没发，今天睡了一天，晚上搞

**Comment by singularity2000** [comment]
大佬更新了吗👀

**Comment by ilharp** [comment]
我还在上这个 b 班，这两天没怎么回家，也没时间测

之后我先抽时间把新版传上来吧，能不能用我也不太清楚

**Comment by ilharp** [comment]
新版传上来了，在 [Repo 页](https://github.com/bakyrd/QQScreenshotSwitch) 点绿色的 Code，然后点最下面的 `Download ZIP` 就行了。

可以先试试能不能用，不能用的话我之后有时间回家了再修

**Comment by forgetmelodyXL** [comment]
用不了

**Comment by KevinCharlie** [comment]
老哥啥时候修呀？

**Comment by ilharp** [comment]
[v1.0.5](https://github.com/bakyrd/QQScreenshotSwitch/releases/tag/v1.0.5) 已发布，适配目前所有版本 QQ，已在 27333、27391、27556、27597、28060 上测试通过。各位可以试一下，没问题就可以关 issue 了

![image](https://github.com/user-attachments/assets/c8a028e0-1988-4291-99f3-5cf6b10ffe21)

---

另外提醒：目前（9 月 14 号）推荐停留在 27597 版本
