### ISSUE TITLE
QQNT再次更新，插件再次失效

### ISSUE THREAD

**Issue by YuiYuK1** [bakyrd/QQScreenshotSwitch#5]
#4 与此症状相同，qq在配置文件为非noop时始终在点击“登录”后就崩溃，无法正常启动
![image](https://github.com/user-attachments/assets/3293fed3-f303-4c07-8bff-878fd62623e6)
（使用旧版截图主要是新版截图因为不知道为什么，在第一次截图后，截出来的图就是灰屏）
like this:
![image](https://github.com/user-attachments/assets/c216c235-430b-4307-b44a-9fd45ae0af19)

**Comment by YuiYuK1** [comment]
![image](https://github.com/user-attachments/assets/81cca651-a845-4fbd-8b54-31e31268e85c)
qq版本为28498版本（我知道版本问题在上个issue中被提及，仅反馈）

**Comment by ilharp** [comment]
实际上 10 月 9 号的时候就失效了，一直没人提我也一直没修

最近找个时间修

**Comment by YuiYuK1** [comment]
> 实际上 10 月 9 号的时候就失效了，一直没人提我也一直没修
> 
> 最近找个时间修

我也是今天重装完电脑才发现有这个问题 谢谢老哥了

**Comment by ilharp** [comment]
![image](https://github.com/user-attachments/assets/298d58ff-5574-4d05-93d8-fcb35bfddc01)

不对，你是不是根本没升级插件到最新版……我就说为啥过了这么久还是只有你一个人反馈这个问题……

我测了 v1.0.5 的 QQScreenshotSwitch 是支持 28498 的

**Comment by YuiYuK1** [comment]
> ![image](https://private-user-images.githubusercontent.com/20179549/382363131-298d58ff-5574-4d05-93d8-fcb35bfddc01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MDkzNDAsIm5iZiI6MTczMDUwOTA0MCwicGF0aCI6Ii8yMDE3OTU0OS8zODIzNjMxMzEtMjk4ZDU4ZmYtNTU3NC00ZDA1LTkzZDgtZmNiMzViZmRkYzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDAwNTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzlmMTBiMTU1ZmRmZjJhNmM3ZDFmMzRmODYyMTczMzYyZjg5ZTIyNzc1ZDM1NzE5ZjliNGEzNzg2NzNkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ga8pyXrUhDGkimHVUQ4TFahzfvIy62mtYQLCR7U29zM)
> 
> 不对，你是不是根本没升级插件到最新版……我就说为啥过了这么久还是只有你一个人反馈这个问题……
> 
> 我测了 v1.0.5 的 QQScreenshotSwitch 是支持 28498 的

我也有点奇怪，在我的笔记本上是好的，但在我的台式机上一直崩溃，但我台式机后重装的系统，应该不会这么不小心吧，等我明天回学校看看吧

**Comment by JustInfLOL** [comment]
> ![image](https://private-user-images.githubusercontent.com/20179549/382363131-298d58ff-5574-4d05-93d8-fcb35bfddc01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MDkzNDAsIm5iZiI6MTczMDUwOTA0MCwicGF0aCI6Ii8yMDE3OTU0OS8zODIzNjMxMzEtMjk4ZDU4ZmYtNTU3NC00ZDA1LTkzZDgtZmNiMzViZmRkYzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDAwNTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzlmMTBiMTU1ZmRmZjJhNmM3ZDFmMzRmODYyMTczMzYyZjg5ZTIyNzc1ZDM1NzE5ZjliNGEzNzg2NzNkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ga8pyXrUhDGkimHVUQ4TFahzfvIy62mtYQLCR7U29zM)
> 
> 不对，你是不是根本没升级插件到最新版……我就说为啥过了这么久还是只有你一个人反馈这个问题……
> 
> 我测了 v1.0.5 的 QQScreenshotSwitch 是支持 28498 的

我也有点奇怪，在我的笔记本上是好的，但在我的台式机上一直崩溃，但我台式机后重装的系统，应该不会这么不小心吧，等我明天回学校看看吧

**Comment by YuiYuK1** [comment]
还真是我的锅。。台式机的UserData全放在d盘，根本不知道更没更新。。抱歉打扰了
